/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Admin' at '4/6/17 1:05 PM' with Gradle 2.14.1
 *
 * @author Admin, @date 4/6/17 1:05 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
